- name: update source list
  file:
    path: /etc/apt/sources.list.d/elastic-7.x.list
    state: touch
  register: source

- name: add http package
  lineinfile:
    path: /etc/apt/sources.list.d/elastic-7.x.list
    line: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
  when: source.diff.before.state == 'absent'

- name: Add PGP key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: update
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
  when: source.diff.before.state == 'absent'

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present
  when: source.diff.before.state == 'absent'

- name: config
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: elastic_start

# ## ALTERNATIVE USING DOCKER ##
# - name: elastic_container
#   docker_container:
#     name: elastic
#     image: "docker.elastic.co/elasticsearch/elasticsearch:{{version_elastic}}"
#     state: started
#     ports:
#       - 9200:9200
#       - 9300:9300
#     env:
#       discovery.type: single-node
