- name: add apt-repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
    codename: bionic

- name: update
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install gdebi-core
  apt:
    name: gdebi-core
    state: present

- name: copy tableau server
  copy:
    src: roles/tableau/debian_install/tableau-server-2019-1-10_amd64.deb
    dest: /home/{{user_tableau}}/tableau-server-2019-1-10_amd64.deb


- name: verify tableau install
  stat:
    path: /etc/tableau
  register: verif

- name: install tableau server
  command:
    cmd: "./gdebi -n /home/{{user_tableau}}/tableau-server-2019-1-10_amd64.deb"
    chdir: /usr/share/gdebi/
  when: verif.stat.exists == false

- name: configure tableau
  command: sudo /opt/tableau/tableau_server/packages/scripts.20191.19.1110.1721/initialize-tsm -f --accepteula
  become_user: "{{user_tableau}}"
  when: verif.stat.exists == false
